default: &default
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%= ENV["REP_DB_NAME"] %>
  username: <%= ENV["REP_DB_USERNAME"] %>
  password: <%= ENV["REP_DB_PASSWORD"] %>
  host: <%= ENV["REP_DB_HOST"] %>

local:
  <<: *default

development:
  <<: *default

develop:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
